#!/bin/bash
# Original author: purpleleaf (max@ganoia.eu)
#
#    License: Creative Commons Attribution 4.0 International (CC BY 4.0)
#    https://creativecommons.org/licenses/by/4.0/
#
#    You are free to:
#        Share - copy and redistribute the material in any medium or format
#        Adapt - remix, transform, and build upon the material for any purpose
#
#
######################################################################

# Dependencies: feh

DIR="$1"

INTERVAL="$2"

if ! [[ "$INTERVAL" =~ ^[0-9]+$ ]]
  then
     INTERVAL="15"
fi

while true; do
	LIST=(`find "$DIR" -type f \( -name '*.jpg' -o -name '*.png' \)`)
	RANDOM=$$$(date +%s)
	WALLPAPER=${LIST[$RANDOM % ${#LIST[@]}]}
	/usr/bin/feh --bg-scale "$WALLPAPER"
	sleep ${INTERVAL}m
done

