#!/bin/bash
# Original author: purpleleaf (max@ganoia.eu)
#
#    License: Creative Commons Attribution 4.0 International (CC BY 4.0)
#    https://creativecommons.org/licenses/by/4.0/
#
#    You are free to:
#        Share - copy and redistribute the material in any medium or format
#        Adapt - remix, transform, and build upon the material for any purpose
#
#
######################################################################

# Dependencies: feh

wallpaper_dir="$1"
interval="$2"
do_lock="$3"

if ! [[ "$interval" =~ ^[0-9]+$ ]]
  then
     interval="15"
fi

while true; do
	list=(`find "$wallpaper_dir" -type f \( -name '*.jpg' -o -name '*.png' \)`)
	random=$$$(date +%s)
	wallpaper=${list[$random % ${#list[@]}]}
	/usr/bin/feh --bg-scale "$wallpaper"
	if $do_lock
	then
		/usr/bin/betterlockscreen -u $wallpaper &
	fi
	sleep ${interval}m
done
