#!/bin/bash
# Original author: purpleleaf (max@ganoia.eu)
#
#    License: Creative Commons Attribution 4.0 International (CC BY 4.0)
#    https://creativecommons.org/licenses/by/4.0/
#
#    You are free to:
#        Share - copy and redistribute the material in any medium or format
#        Adapt - remix, transform, and build upon the material for any purpose
#
######################################################################

PATH=$1
DIR=${PATH%/*}
FILE=${PATH##*/}
THUMB_DIR=`/usr/bin/xdg-user-dir PICTURES`"/.thumb"
THUMB=$THUMB_DIR/thumb-$FILE

if [ ! -d "$THUMB_DIR" ]; then
/usr/bin/mkdir $THUMB_DIR
fi

if [ ! -f "$THUMB" ]; then
  /usr/bin/convert $1 -resize 19% $THUMB
fi
echo  -n $THUMB

